project:
  type: website

title: "ParallelProcessing"
editor: visual

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ParallelComputing.qmd
        text: Parallel Computing
      - href: git.qmd
        text: Git Intro

format:
  html:
    theme: cosmo

